Math-Magicians (Project)
rahimialijan/math-magicians pull request #6
Opened 2023-06-14 13:09 UTC by rahimialijan

# Math-Magicians Project (Testing the Logics)

- Installed the jest for my project.
- Create a calculate.test.js file to test my Calculate function inside the calculate.js file
- Create an operate.test.js file to test my operate function inside the operate.js file.

2023-06-14 14:53 UTC, Munsa1 requested changes
Hi @rahimialijan @supreeti, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Passing Linters :heavy_check_mark: 
Correct GitHub Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._
 ### Due to insufficient files changed I will leave some comments here
- [ ] Kindly remove the link to the `Live Demo` section as you have removed the section itself and this link has become broken
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/b8b8d828-eaef-414f-a903-2a2c7b7c2adc)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Going forward kindly Capitalize the first letter of the first word of your commit messages

- [ ] Also you can consider adding your coding partner as a co-author to the author section of the readme file
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/978f98ce-b86d-4d85-bb49-77bb15e602cb)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 14:53 UTC, Munsa1 commented on src/components/Calculator/logic/operate.test.js
> +});
- [ ] ll the functionalities & scenarios of the operate.js should be covered using Jest. Kindly ensure that the following scenarios are tested as well.
- Multiplication of two numbers should return the correct value.
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/8b7e5521-5ff2-4f10-8537-805eeeb3d76a)

- Subtraction of two numbers should return the correct value.
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/35abbc32-4b45-441c-9ac3-4091d0e05af9)

- A Number cannot be divided by o
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/b098d692-d9bd-46ab-bb9f-30a24ce21962)

- A test for the `%` Modulus operation
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/f23da171-6cc0-4205-b080-f7c01300c7ef)

- Kindly do not edit the `operate.js` file as we have to test for a case where we cannot find the `%` modulus of a number by `0`. Your `operate.js` file is missing this logic, kindly add it and test for this.

Your Operate.js
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/09548748-db81-4fa3-9ec5-97c13fa90864)


Given Operate.js
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/097a858c-0b37-48fc-b525-e406727ef895)

We need to test that `you can't find modulo as can't divide by 0`.
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/6410cf10-49f3-4a0b-8b5c-b75a048c56e8)


- A test for an unknown operation should also be covered.
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/44229a20-034f-49af-94b0-3bf3cffaa2db)

2023-06-14 14:53 UTC, Munsa1 commented on src/components/Calculator/logic/calculate.test.js
> +});
- [ ] Good job adding a calculate.js test, however, we have to test all scenarios of the `calculate.test.js`. We have also been advised to use React Testing Library to simulate user interaction for these tests.
Kindly ensure you add tests for the scenarios in calculate.js including:
- What happens when a user clicks the `.` point operand
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/fddba474-7b9a-4891-9543-2f30e7556231)

- what happens when the user clicks the `-/+` negative slash positive operand
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/1679d44f-241d-4b3e-9358-0c5abfba0eea)

- If there is no operation, update next and clear the value
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/286cccd7-2248-4e71-88d1-92554f9816ce)

- If there is an operation, update next
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/98d20cd2-16ac-4560-bac5-b5eaa3c0b6c9)

- User pressed an operation after pressing '='
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/e9af3841-2e23-4aec-b144-ab3b30454c1b)

- What happens when a user pressed an operation button and there is an existing operation
![image](https://github.com/rahimialijan/math-magicians/assets/81932478/0ac497e8-11a9-4e48-956f-ab537e3ec6c1)

2023-06-14 14:53 UTC, Munsa1 commented on src/components/Calculator/logic/calculate.test.js
> +  expect(newState).toEqual(expectedState);
- [ ] React Testing Library should be used to simulate user interaction for this test

2023-06-14 14:57 UTC, Munsa1 commented
- [ ] Kindly note that you should have Jest snapshots for testing all the components in your app. These include `HomePage`, `quotes`, and the `Calculator` component itself. This is a requirement, and I have left it here due to insufficient files being changed.

2023-06-15 08:50 UTC, AdnanOlarmmi approved these changes
Hi @rahimialijan and @supreeti,
This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- Handle all tests edge cases.

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 08:58 UTC, merged